### ISSUE TITLE
Please upgrade Groovy to the latest version (2.4.0)

### ISSUE THREAD

**Issue by cooniur** [JFrogDev/artifactory-user-plugins#26]
Please upgrade Groovy library version from 1.8 to the latest (2.4.0) to support running in JVM 8.

**Comment by echohack** [comment]
+1 on this. @cooniur I can understand your frustration, so let's keep things civil here for whatever kind developer might be looking at this issue. :)

This is an important issue because support for Java 7 will be dropped in April 2015:

http://www.oracle.com/technetwork/java/eol-135779.html

> As outlined in the Oracle JDK Support Roadmap, after April 2015, Oracle will not post further updates of Java SE 7 to its public download sites. Customers who need continued access to critical bug fixes and security fixes as well as general maintenance for Java SE 7 or older versions can get long term support through Oracle Java SE Support. The process of migrating users from Java 7 to Java 8 through the auto update feature is expected to take place after the January 2015 CPU release.


Build sync will fail using JVM 8 at the moment.

Error log:
2015-03-25 12:21:34,832 [http-bio-8081-exec-5] [INFO ] (buildSync           :-1) - Downloading JSON build info http://example.artifactory.com/artifactory/api/build/REDACTED/6 [started:2013-06-03T08:44:08.882-0700]
2015-03-25 12:21:34,963 [http-bio-8081-exec-5] [INFO ] (buildSync           :-1) - Deploying locally build REDACTED:6:2013-06-03T08:44:08.882-0700
2015-03-25 12:21:34,982 [http-bio-8081-exec-5] [WARN ] (buildSync           :278) - Insertion of build  REDACTED:6:2013-06-03T08:44:08.882-0700 failed due to: No signature of method: com.sun.proxy.$Proxy30.invokeInTransaction() is applicable for argument types: (LocalBuildService$1) values: [LocalBuildService$1@3efbbd93]
Possible solutions: invokeInTransaction(java.lang.String, java.util.concurrent.Callable)
groovy.lang.MissingMethodException: No signature of method: com.sun.proxy.$Proxy30.invokeInTransaction() is applicable for argument types: (LocalBuildService$1) values: [LocalBuildService$1@3efbbd93]
Possible solutions: invokeInTransaction(java.lang.String, java.util.concurrent.Callable)
                at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:55) ~[groovy-1.8.8.jar:1.8.8]
                at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46) ~[groovy-1.8.8.jar:1.8.8]
                at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116) [groovy-1.8.8.jar:1.8.8]
                at LocalBuildService.addBuild(buildSync.groovy:547) ~[script:na]
                at LocalBuildService$addBuild.call(Unknown Source) [script:na]
                at buildSync$_doSync_closure4.doCall(buildSync.groovy:278) [script:na]
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40]
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40]
                at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
                at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90) [groovy-1.8.8.jar:1.8.8]
                at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233) [groovy-1.8.8.jar:1.8.8]
                at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:272) [groovy-1.8.8.jar:1.8.8]
                at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:901) [groovy-1.8.8.jar:1.8.8]
                at groovy.lang.Closure.call(Closure.java:415) [groovy-1.8.8.jar:1.8.8]
                at groovy.lang.Closure.call(Closure.java:428) [groovy-1.8.8.jar:1.8.8]
                at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1379) [groovy-1.8.8.jar:1.8.8]
                at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1351) [groovy-1.8.8.jar:1.8.8]
                at org.codehaus.groovy.runtime.dgm$170.invoke(Unknown Source) [groovy-1.8.8.jar:1.8.8]
                at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271) [groovy-1.8.8.jar:1.8.8]
                at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53) [groovy-1.8.8.jar:1.8.8]
                at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42) [groovy-1.8.8.jar:1.8.8]
                at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108) [groovy-1.8.8.jar:1.8.8]
                at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116) [groovy-1.8.8.jar:1.8.8]
                at buildSync.doSync(buildSync.groovy:261) [script:na]
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40]
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40]
                at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
                at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90) [groovy-1.8.8.jar:1.8.8]
                at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233) [groovy-1.8.8.jar:1.8.8]
                at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:361) [groovy-1.8.8.jar:1.8.8]
                at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:901) [groovy-1.8.8.jar:1.8.8]
                at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:721) [groovy-1.8.8.jar:1.8.8]
                at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:44) [groovy-1.8.8.jar:1.8.8]
                at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:423) [groovy-1.8.8.jar:1.8.8]
                at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:348) [groovy-1.8.8.jar:1.8.8]
                at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:901) [groovy-1.8.8.jar:1.8.8]
                at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66) [groovy-1.8.8.jar:1.8.8]
                at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:46) [groovy-1.8.8.jar:1.8.8]
                at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133) [groovy-1.8.8.jar:1.8.8]
                at buildSync$_run_closure1_closure5.doCall(buildSync.groovy:156) [script:na]
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40]
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40]
                at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
                at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90) [groovy-1.8.8.jar:1.8.8]
                at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233) [groovy-1.8.8.jar:1.8.8]
                at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:272) [groovy-1.8.8.jar:1.8.8]
                at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:901) [groovy-1.8.8.jar:1.8.8]
                at groovy.lang.Closure.call(Closure.java:415) [groovy-1.8.8.jar:1.8.8]
                at groovy.lang.Closure.call(Closure.java:428) [groovy-1.8.8.jar:1.8.8]
                at org.artifactory.addon.plugin.execution.ExecutePluginImpl.execute(ExecutePluginImpl.java:104) [artifactory-addon-plugins-3.5.3.jar:na]
                at org.artifactory.addon.plugin.ScriptDelegate.execute(ScriptDelegate.java:97) [artifactory-addon-plugins-3.5.3.jar:na]
                at org.artifactory.addon.plugin.GroovyRunnerImpl.execute(GroovyRunnerImpl.java:120) [artifactory-addon-plugins-3.5.3.jar:na]
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40]
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40]
                at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
                at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) [spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
                at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:201) [spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
                at com.sun.proxy.$Proxy69.execute(Unknown Source) [na:na]
                at org.artifactory.addon.plugin.PluginsAddonImpl.execute(PluginsAddonImpl.java:57) [artifactory-addon-plugins-3.5.3.jar:na]
                at org.artifactory.addon.rest.RestAddonImpl.runPluginExecution(RestAddonImpl.java:1026) [artifactory-addon-rest-3.5.3.jar:na]
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40]
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40]
                at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
                at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) [spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
                at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:201) [spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
                at com.sun.proxy.$Proxy114.runPluginExecution(Unknown Source) [na:na]
                at org.artifactory.rest.resource.plugin.PluginsResource.execute(PluginsResource.java:102) [artifactory-rest-3.5.3.jar:na]
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40]
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40]
                at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
                at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) [jersey-server-1.12.jar:1.12]
                at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) [jersey-server-1.12.jar:1.12]
                at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) [jersey-server-1.12.jar:1.12]
                at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288) [jersey-server-1.12.jar:1.12]
                at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) [jersey-server-1.12.jar:1.12]
                at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) [jersey-server-1.12.jar:1.12]
                at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) [jersey-server-1.12.jar:1.12]
                at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) [jersey-server-1.12.jar:1.12]
                at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1483) [jersey-server-1.12.jar:1.12]
                at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1414) [jersey-server-1.12.jar:1.12]
                at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1363) [jersey-server-1.12.jar:1.12]
                at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1353) [jersey-server-1.12.jar:1.12]
                at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:414) [jersey-servlet-1.12.jar:1.12]
                at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537) [jersey-servlet-1.12.jar:1.12]
                at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:708) [jersey-servlet-1.12.jar:1.12]
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:727) [servlet-api.jar:na]
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [catalina.jar:7.0.56]
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.56]
                at org.artifactory.webapp.servlet.RepoFilter.execute(RepoFilter.java:193) [artifactory-web-application-3.5.3.jar:na]
                at org.artifactory.webapp.servlet.RepoFilter.doFilter(RepoFilter.java:87) [artifactory-web-application-3.5.3.jar:na]
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.56]
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.56]
                at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:201) [spring-security-web-3.2.0.RELEASE.jar:3.2.0.RELEASE]
                at org.artifactory.webapp.servlet.authentication.ArtifactoryBasicAuthenticationFilter.doFilter(ArtifactoryBasicAuthenticationFilter.java:91) [artifactory-web-application-3.5.3.jar:na]
                at org.artifactory.webapp.servlet.authentication.ArtifactoryAuthenticationFilterChain.doFilter(ArtifactoryAuthenticationFilterChain.java:138) [artifactory-web-application-3.5.3.jar:na]
                at org.artifactory.webapp.servlet.AccessFilter.authenticateAndExecute(AccessFilter.java:224) [artifactory-web-application-3.5.3.jar:na]
                at org.artifactory.webapp.servlet.AccessFilter.doFilterInternal(AccessFilter.java:184) [artifactory-web-application-3.5.3.jar:na]
                at org.artifactory.webapp.servlet.AccessFilter.doFilter(AccessFilter.java:152) [artifactory-web-application-3.5.3.jar:na]
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.56]
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.56]
                at org.artifactory.webapp.servlet.RequestFilter.doFilter(RequestFilter.java:67) [artifactory-web-application-3.5.3.jar:na]
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.56]
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.56]
                at org.artifactory.webapp.servlet.ArtifactoryFilter.doFilter(ArtifactoryFilter.java:92) [artifactory-web-application-3.5.3.jar:na]
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.56]
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.56]
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) [catalina.jar:7.0.56]
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) [catalina.jar:7.0.56]
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170) [catalina.jar:7.0.56]
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) [catalina.jar:7.0.56]
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [catalina.jar:7.0.56]
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421) [catalina.jar:7.0.56]
                at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070) [tomcat-coyote.jar:7.0.56]
                at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611) [tomcat-coyote.jar:7.0.56]
                at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316) [tomcat-coyote.jar:7.0.56]
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_40]
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_40]
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-coyote.jar:7.0.56]
                at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
2015-03-25 12:21:34,984 [http-bio-8081-exec-5] [INFO ] (buildSync           :-1) - Getting all build numbers from http://example.artifactory.com/artifactory/api/build/REDACTED
2015-03-25 12:21:35,060 [http-bio-8081-exec-5] [INFO ] (buildSync           :-1) - Found 1 remote builds named REDACTED in http://example.artifactory.com/artifactory/
2015-03-25 12:21:35,062 [http-bio-8081-exec-5] [INFO ] (buildSync           :-1) - Found 0 local builds named REDACTED
2015-03-25 12:21:35,062 [http-bio-8081-exec-5] [INFO ] (buildSync           :270) - Found 0 identical builds
2015-03-25 12:21:35,063 [http-bio-8081-exec-5] [INFO ] (buildSync           :-1) - Downloading JSON build info http://example.artifactory.com/artifactory/api/build/REDACTED/83 [started:2013-06-10T10:14:42.165-0700]
2015-03-25 12:21:35,221 [http-bio-8081-exec-5] [INFO ] (buildSync           :-1) - Deploying locally build REDACTED:83:2013-06-10T10:14:42.165-0700
2015-03-25 12:21:35,233 [http-bio-8081-exec-5] [WARN ] (buildSync           :278) - Insertion of build  REDACTED:83:2013-06-10T10:14:42.165-0700 failed due to: No signature of method: com.sun.proxy.$Proxy30.invokeInTransaction() is applicable for argument types: (LocalBuildService$1) values: [LocalBuildService$1@78d344a8]
Possible solutions: invokeInTransaction(java.lang.String, java.util.concurrent.Callable)
groovy.lang.MissingMethodException: No signature of method: com.sun.proxy.$Proxy30.invokeInTransaction() is applicable for argument types: (LocalBuildService$1) values: [LocalBuildService$1@78d344a8]
Possible solutions: invokeInTransaction(java.lang.String, java.util.concurrent.Callable)
                at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:55) ~[groovy-1.8.8.jar:1.8.8]
                at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46) ~[groovy-1.8.8.jar:1.8.8]
                at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116) [groovy-1.8.8.jar:1.8.8]
                at LocalBuildService.addBuild(buildSync.groovy:547) ~[script:na]
                at LocalBuildService$addBuild.call(Unknown Source) [script:na]
                at buildSync$_doSync_closure4.doCall(buildSync.groovy:278) [script:na]
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40]
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40]
                at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
                at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90) [groovy-1.8.8.jar:1.8.8]
                at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233) [groovy-1.8.8.jar:1.8.8]

**Comment by cooniur** [comment]
@echohack Thanks!

**Comment by aseftel** [comment]
The support for Groovy 2.4.x requires a major change in the Artifactory code therefore this will be released on the next Artifactory major version that it's ETA is Q3.

**Comment by aseftel** [comment]
Artifactory 4.x was released and supports groovy 2.4.

Feel free to upgrade to the latest version of Artifactory to enjoy the new UI and the added features.

**Comment by cooniur** [comment]
@aseftel Thanks for the follow-up! That's awesome!
