### ISSUE TITLE
Request support for Artifactory v5

### ISSUE THREAD

**Issue by osenbach** [JFrogDev/artifactory-user-plugins#76]
Hello,

Is support for Artifactory v5 on the roadmap?

**Comment by DarthFennec** [comment]
Yes, Artifactory 5 support is very important to us. We've been working hard toward getting each of the plugins in this repository tested and working in Artifactory 5, but as there are about a hundred of them, it's a long process. If there's a plugin in particular that you're worried about, or if you find that a plugin you use doesn't work properly in version 5, you can open an issue, and we'll see what we can do to get to that one as soon as possible. As it stands for now, I believe that most of these should work in version 5 just as they are.

**Comment by osenbach** [comment]
Thanks @DarthFennec .  I'll give the Helm plugin a go on v5 and report back to at least update the readme and indicate general support.

**Comment by specialgoods** [comment]
Using artifactory 5.2.1 - Cannot cast object 'true' with class 'java.lang.Boolean' to class 'int'

**Comment by DarthFennec** [comment]
@specialgoods Can you specify which plugin you're having trouble with?

**Comment by specialgoods** [comment]
Sorry - I should have been more clear. 

We successfully utilized https://github.com/JFrogDev/artifactory-user-plugins/blob/master/cleanup/artifactCleanup/artifactCleanup.groovy in v4.13.2. Upgrading to 5.2.1 has caused this error to result when Artifactory attempts to load the plugin from the plugins dir:

2017-06-27 20:01:04,560 [art-groovy-plugins-reloader] [INFO ] (o.a.a.p.GroovyRunnerImpl:244) - Loading script from 'artifactCleanup.groovy'.
2017-06-27 20:01:04,561 [art-groovy-plugins-reloader] [WARN ] (o.a.a.p.e.ExecutePluginImpl:184) - Overriding existing execution with name. 'cleanup'.
2017-06-27 20:01:04,562 [art-groovy-plugins-reloader] [INFO ] (o.a.a.p.e.ExecutePluginImpl:187) - Groovy execution 'cleanup' has been successfully registered.
2017-06-27 20:01:04,562 [art-groovy-plugins-reloader] [WARN ] (o.a.a.p.e.ExecutePluginImpl:184) - Overriding existing execution with name. 'cleanupCtl'.
2017-06-27 20:01:04,562 [art-groovy-plugins-reloader] [INFO ] (o.a.a.p.e.ExecutePluginImpl:187) - Groovy execution 'cleanupCtl' has been successfully registered.
2017-06-27 20:01:04,579 [art-groovy-plugins-reloader] [INFO ] (artifactCleanup     :75) - Schedule job policy list: [[0 0 5 ? * 1, [libs-releases-local], 3, true]]
2017-06-27 20:01:04,583 [art-groovy-plugins-reloader] [ERROR] (o.a.a.p.GroovyRunnerImpl:300) - Error loading script from 'artifactory/etc/plugins/artifactCleanup.groovy'.
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'true' with class 'java.lang.Boolean' to class 'int'
        at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToNumber(DefaultTypeTransformation.java:163) ~[groovy-all-2.4.5.jar:2.4.5]
        at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.intUnbox(DefaultTypeTransformation.java:69) ~[groovy-all-2.4.5.jar:2.4.5]
        at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToPrimitive(DefaultTypeTransformation.java:332) ~[groovy-all-2.4.5.jar:2.4.5]

**Comment by DarthFennec** [comment]
@specialgoods Judging from the error message, your `artifactCleanup.properties` file appears to specify:

```json
policies = [["0 0 5 ? * 1", ["libs-releases-local"], 3, true]]
```

The example in the default properties file is:

```json
policies = [["0 0 5 ? * 1", ["libs-releases-local"], 3, 500, true]]
```

That `500` is a number of milliseconds to pause between deletions. You don't seem to have it in your configuration, but you do have a `true`, which it tries to read as a millisecond count. Hence the `Cannot cast object 'true' with class 'java.lang.Boolean' to class 'int'`: It's trying to convert `true` to an integer and it can't. If you put a pause time in your configuration (`0` should work if you don't want it to pause at all), the error should go away.

I hope this helps! Let me know if you have any further questions.

**Comment by specialgoods** [comment]
Nice catch! TYVM

**Comment by DarthFennec** [comment]
This seems to be resolved, so I'll close it now. If you have any further problems with plugins and Artifactory 5.x, don't hesitate to open a new issue.
